### ISSUE TITLE
typo in line 9 of 10 script

### ISSUE THREAD

**Issue by IMMyers** [ganlbarone/FV2Keys#3]
There appears to be a typo in line 9. As it reads now it is:
        $auth = Invoke-WebRequest -SessionVariable Sessions -UseBasicParsing -Uri "$serverAddress/?failover'" -Body $data -Method "Post" -ErrorAction Stop

For this to work I had to change it to: 
        $auth = Invoke-WebRequest -SessionVariable Sessions -UseBasicParsing -Uri "$serverAddress/?failover" -Body $data -Method "Post" -ErrorAction Stop

Note the absence of the single quote after failover. Without this correction, mine kept trying to send me to the SSO login, but with it I was able to retrieve the FV key.

I noticed something else as well. If using a Jamf-hosted cloud instance for your JSS, port 8443 does not work, but port 443 does. You may want to set this as a separate variable or note it with a comment.

**Comment by ganlbarone** [comment]
Thanks for catching this. On my personal version of this. I had this same typo, however in my own version I dont parameterize the $serverAddress. Which is likely why it never caused issue for me, and also why I never caught it. This was a good catch. I updated both versions of the code to fix this bug, I also added an additional comment concerning ports 8443 vs 443. We use an on prem server so that is all I had to test with when writing this, we dont have a hosted cloud instance from them. 

Thanks for the notes\feedback on this, glad it works for you.
